# Generated by Django 5.0.1 on 2024-02-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Derivados',
            fields=[
                ('id_derivado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Derivados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flores',
            fields=[
                ('id_flores', models.AutoField(primary_key=True, serialize=False)),
                ('cepa', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('porcent_comp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Flores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parafernalia',
            fields=[
                ('id_parafernalia', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Parafernalia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=3000, null=True)),
                ('img', models.CharField(blank=True, max_length=1000, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('numvendidos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semillas',
            fields=[
                ('id_semillas', models.AutoField(primary_key=True, serialize=False)),
                ('cepa', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Semillas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('fechareg', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
